name       : libpsl
version    : 0.21.1
release    : 5
source     :
    - https://github.com/rockdaboot/libpsl/releases/download/0.21.1/libpsl-0.21.1.tar.lz : 644375d557bb3b84c485df2dae98ee388fe1e11fb75230004e4b8623b3b833a9
license    : MIT
component  : programming.library
summary    : C library to handle the Public Suffix List
description: |
    PC library to handle the Public Suffix List
emul32     : yes
builddeps  :
    - pkgconfig32(icu-uc)
    - pkgconfig32(libidn2)
    - pkgconfig32(libidn)
    - libunistring-32bit-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
